apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deployment
  labels:
    app: grpc-server-deployment
spec:
  selector:
    matchLabels:
      app: grpc-server-deployment
  replicas: 4
  template:
    metadata:
      labels:
        app: grpc-server-deployment
    spec:
      containers:
        - name: grpc-server
          image: racarlosdavid/grpc_server
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-server-deployment
  name: svc-grpc-server
spec:
  type: ClusterIP
  selector:
    app: grpc-server-deployment
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-deployment
  labels:
    app: grpc-client-deployment
spec:
  selector:
    matchLabels:
      app: grpc-client-deployment
  replicas: 4
  template:
    metadata:
      labels:
        app: grpc-client-deployment
    spec:
      containers:
        - name: grpc-client-api
          image: racarlosdavid/grpc_client_api
          env:
          - name: HOST
            value: svc-grpc-server
          ports:
            - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-client-deployment
  name: svc-grpc-client
spec:
  type: LoadBalancer
  selector:
    app: grpc-client-deployment
  ports:
    - port: 80
      targetPort: 2000
      protocol: TCP